api-version: 1.18
name: WarpGUITools
version: 3.0
author: Jakey099
main: me.jakey099.WarpGUITools.Main
description: WarpGUI tools for easy teleport GUI setup

commands:
  warp:
    description: this is the warp menu command accessible to all players